### get all the categories with index action
GET http://localhost:3000/categories

### Get all the posts from index action
GET http://localhost:3000/posts

### get request with the valid id for post  
GET http://localhost:3000/posts/1


### get request with the invalid id for post  
GET http://localhost:3000/posts/20

### create a post with token
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzczMTgxMDF9.dRjwM78VhX56tmbTadnX_71jaFhWds4k1COMYnqpR14"

{
  "title": "Dnay1 created me",
  "content": "I have been created with dany 1",
  "category_id": 1
}


### create a post without token
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "I'm not authenticate",
  "content": "oh",
  "category_id": 1
}


### update a post with token
PUT http://localhost:3000/posts/16
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzczMTgyNTl9.bGnGtdcWJ5a17KSocCwC3LcU3gQdRNpEinOnx0RXFPU"

{
  "title": "First edited me",
  "content": "I've been edited with token and first user!!!!",
  "category_id": 1
}


### update a post without token
PUT http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "I'm the edited one again",
  "content": "I've been edited with token",
  "category_id": 4
}


### delete post with token 
DELETE http://localhost:3000/posts/3
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzczMTc2NTZ9.9WK_rRTFlJ9VETf4b5m6IQ_gZx_IM2Vo6dJ3BdXlme0"




### register a user 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "Dany1",
  "email": "dany1@test.com",
  "password": "121212",
  "password_confirmation": "121212"
}



### login user with correct credentails 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "login": "first", 
  "password": "121212"
}


### login user with incorrect credentails 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "first@test.com", 
  "password": "111111"
}


