### get all the categories with index action
GET http://localhost:3000/categories

### Get all the posts from index action
GET http://localhost:3000/posts

### get request with the valid id for post  
GET http://localhost:3000/posts/1


### get request with the invalid id for post  
GET http://localhost:3000/posts/20

### create a post with token
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzcyOTM4Nzd9.XDlc195XTmxRMOEA8-gglyjYSIGLZKyIljFK1Fu2Qh8"

{
  "title": "I'm authenticate",
  "content": "Testing",
  "category_id": 1
}


### create a post without token
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "I'm not authenticate",
  "content": "oh",
  "category_id": 1
}



### register a user 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "Dany1",
  "email": "dany1@test.com",
  "password": "121212",
  "password_confirmation": "121212"
}



### login user with correct credentails 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "login": "first", 
  "password": "121212"
}


### login user with incorrect credentails 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "first@test.com", 
  "password": "111111"
}


